# Generated by Django 5.1.6 on 2025-02-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='playlist_song',
            new_name='PlaylistSong',
        ),
        migrations.RenameModel(
            old_name='playlist_user',
            new_name='PlaylistUser',
        ),
    ]
