# Generated by Django 5.1.6 on 2025-02-09 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_rename_playlist_song_playlistsong_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ['-pk'], 'verbose_name': 'Playlist Song', 'verbose_name_plural': 'Playlist Songs'},
        ),
        migrations.AlterModelOptions(
            name='playlistuser',
            options={'ordering': ['-pk'], 'verbose_name': 'Playlist User', 'verbose_name_plural': 'Playlist Users'},
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted?'),
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='playlistuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='playlistuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='playlistuser',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Deleted?'),
        ),
        migrations.AddField(
            model_name='playlistuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterModelTable(
            name='playlistsong',
            table='playlistsongs',
        ),
        migrations.AlterModelTable(
            name='playlistuser',
            table='playlistusers',
        ),
    ]
